export const SET_LANG = 'SET_LANG';
export const SET_INTERNET_CONNECTION = 'SET_INTERNET_CONNECTION';
export const REFRESH_LIST = 'REFRESH_LIST';
export const SET_LOADING_OVERLAY_STATUS = 'SET_LOADING_OVERLAY_STATUS';

export const SET_LOCATION = 'SET_LOCATION';
export const RESET_LOCATION = 'RESET_LOCATION';
export const SET_GPS_STATUS = 'SET_GPS_STATUS';

export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FB_FAIL = 'LOGIN_FB_FAIL';
export const LOGIN_RESET_ERROR = 'LOGIN_RESET_ERROR';
export const LOGOUT = 'LOGOUT';

export const SELECT_TAB = 'SELECT_TAB';
export const DELIVARY_PLACE_SELECT_TAB = 'DELIVARY_PLACE_SELECT_TAB';

export const UNSEEN_MESSAGE_COUNT_SET = 'UNSEEN_MESSAGE_COUNT_SET';
export const UNSEEN_MESSAGES_COUNT_RESET = 'UNSEEN_MESSAGES_COUNT_RESET';
export const SET_CONVERSATION_ID = 'SET_CONVERSATION_ID';
export const RE_SET_CONVERSATION_ID = 'RE_SET_CONVERSATION_ID';

export const SEEN_NOTIFICATION_REQUEST = ' SEEN_NOTIFICATION_REQUEST';
export const SEEN_NOTIFICATION_SUCCESS = ' SEEN_NOTIFICATION_SUCCESS';
export const SEEN_NOTIFICATION_FAIL = ' SEEN_NOTIFICATION_FAIL';

export const CLEAR_NOTIFICATIONS = 'CLEAR_NOTIFICATIONS';

export const UNSEEN_NOTIFICATION_COUNT_SET = 'UNSEEN_NOTIFICATION_COUNT_SET';
export const UNSEEN_NOTIFICATION_COUNT_RESET =
  'UNSEEN_NOTIFICATION_COUNT_RESET';

export const SET_SETTINGS = 'SET_SETTINGS';
export const CLEAR_SETTINGS = 'CLEAR_SETTINGS';
export const SET_WALLET = 'SET_WALLET';
export const CLEAR_WALLET = 'CLEAR_WALLET';
export const RESET_FLAG = 'RESET_FLAG';

// export const SETTINGS = 'SETTINGS';
