export default {
  text: {
    color: '#484848',
    size: 5.5,
    translateNumbers: false,
  },
  indicator: {
    size: 8,
    color: 'primary',
  },
  icon: {
    size: 7,
    color: '#484848',
    type: 'ion',
  },
  button: {
    size: 5.5,
    color: 'white',
    bold: true,
    backgroundColor: 'button',
    borderRadius: 8,
    elevation: 0,
    paddingVertical: 5,
    paddingHorizontal: 5,
    disabledColor: '#f3f4f5',
    disabledBackgroundColor: 'disabled',
  },
  image: {
    resizeMode: 'cover',
    progressColor: 'primary',
    errorColor: 'black',
    errorBackgroundColor: 'rgba(0, 0, 0, 0.2)',
  },
  inputError: {
    color: 'white',
    sizeScale: 0.7,
  },
  input: {
    size: 5,
    activeColor: '#8A8A8A',
    inactiveColor: 'grey',
    color: '#484848',
    backgroundColor: 'white',
    placeholderColor: '#858F96',
    center: false,
    translateNumbers: true,
    paddingHorizontal: 3,
    pv: 3,
    bc: 'inputBorderColor',
    bw: 1,
    borderRadius: 5,
    height: 7.5,
  },
  input2: {
    size: 5,
    activeColor: '#8A8A8A',
    inactiveColor: 'grey',
    color: '#484848',
    backgroundColor: 'white',
    // backgroundColor: 'rgba(0,0,0,0.3)',
    placeholderColor: '#858F96',
    center: false,
    translateNumbers: true,
    paddingHorizontal: 3,
    pv: 3,
    bc: 'inputBorderColor',
    // bc: 'rgba(0,0,0,0.8)',
    bw: 1,
    borderRadius: 15,
    height: 6.5,
    elevation: 3,
  },
  formInputFrame: {
    size: 5,
    placeholderColor: '#858F96',
    pv: 4,
    ph: 4,
    bc: 'inputBorderColor',
    bw: 1,
    borderRadius: 4,
    height: 7.5,
  },
  textArea: {
    size: 6,
    color: '#484848',
    backgroundColor: 'white',
    placeholderColor: '#858F96',
    height: 20,
    pv: 4,
    ph: 4,
    bc: 'inputBorderColor',
    bw: 1,
    borderRadius: 4,
    translateNumbers: false,
    underlineColor: 'transparent',
  },
  picker: {
    size: 5,
    color: '#484848',
    backgroundColor: 'white',
    placeholderColor: '#858F96',
    pv: 3,
    ph: 4,
    bc: 'inputBorderColor',
    bw: 1,
    borderRadius: 4,
    height: 6.5,
    disalbedBackgroundColor: '#E6E8EA',
  },
  wheelPicker: {
    size: 5,
    color: '#484848',
    backgroundColor: 'white',
    paddingVertical: 4,
    borderRadius: 4,
    height: 7.5,
    placeholderColor: '#858F96',
    borderColor: 'inputBorderColor',
    borderWidth: 1,
  },
  datePicker: {
    size: 5,
    color: '#484848',
    backgroundColor: 'white',
    paddingVertical: 4,
    bc: 'inputBorderColor',
    borderWidth: 1,
    borderRadius: 4,
    height: 7.5,
    placeholderColor: '#858F96',
  },
  radioButton: {
    activeColor: 'primary',
    normalColor: '#484848',
    size: 6.5,
    labelColor: 'black',
    labelSize: 5.5,
  },
  checkBox: {
    activeColor: 'primary',
    normalColor: '#484848',
    size: 7.5,
    labelColor: 'black',
    labelSize: 5.5,
  },
  toggleButtons: {
    activeBackgroundColor: 'primary',
    inActiveBackgroundColor: 'white',
    activeColor: 'white',
    inActiveColor: '#979797',
    activeBorderColor: 'primary',
    inActiveBorderColor: '#979797',
  },
  list: {
    indicatorColor: 'primary',
    errorLabelColor: 'error',
    noResultsLabelColor: 'black',
    retryButtonBackgroundColor: 'primary',
    retryButtoncolor: 'white',
  },
  tabBar: {
    height: 7,
    backgroundColor: 'primary',
    activeTextColor: 'white',
    activeTextSize: 5,
    activeTextBold: true,
    inactiveTextColor: 'rgba(255, 255, 255, 0.6)',
    inactiveTextSize: 5,
    inactiveTextBold: false,
    underlineColor: 'secondary',
    underlineHeight: 4,
  },
  swiper: {
    indicatorColor: 'rgba(255, 255, 255, 0.5)',
    indicatorActiveColor: 'rgba(255, 255, 255, 1)',
  },
  localNotifications: {
    info: {
      backgroundColor: '#333',
      closeColor: 'primary',
    },
    success: {
      backgroundColor: 'safe',
      closeColor: 'white',
    },
    error: {
      backgroundColor: 'error',
      closeColor: 'white',
    },
  },
};
